### ISSUE TITLE
你好哥 启动的时候报错了 是不是这个系统配置的位置不对啊大哥

### ISSUE THREAD

**Issue by WangZhiChao66** [BeammNotFound/get-jobs-boss#1]
![image](https://github.com/BeammNotFound/get-jobs-boss/assets/69849636/e00096b1-cbb7-4865-9184-0d962e1c13b1)

he path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html

**Comment by BeammNotFound** [comment]
要替换成你自己下载的chromedriver的路径
